[project]
name = "vlsp2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Khanh Nguyen", email = "mailcuakhanhowo@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "faiss-cpu>=1.15.1",
    "pandas>=3.0.6",
    "rank-bm25>=0.2.2",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
vlsp2026 = "vlsp2026:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
